name: suren

on:
  # Execute on every push to any branch
  push:
    branches:
      - "**"
  # Execute on every pull request to the master branch
  pull_request_target:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
      - run: npm install -g dockerfilelint prettier@2.3.0
      - run: dockerfilelint ./web/Dockerfile
      - run: prettier --check .
